specification.md
The first commit is just fixing a typo.
The second commit might be controversial depending on if it was intentional or not to make the job status callback setters for `Executor` and `Job` different.
=> Fix callback example

specification.md
opening the wording slightly to allow the possibility that the management itself is not fully on the exascale machine (perhaps remote)
=> wording change

specification.md
Include a short appendix on the naming and pronunciation. Also adjust
some of the code examples to use the `jpsi` prefix rather than `psij`.
Closes #34
=> naming: change the name to J/PSI

specification.md
This adds a note to `JobExecutor.submit()` that `InvalidJobException` is fatal and also adds `SubmitException.isTransient()` as discussed in #10
=> Update submit exceptions

specification.md
As discussed in #93, the semantics of the `overrideEnvironment` flag are
OK, but the name doesn't immediately evoke the right semantics in many
minds.  Change the name to `inheritEnvironment` to hopefully evoke the
correct semantics in users' minds.
Closes #93
=> change `overrideEnvironment` -> `inheritEnvironment`

specification.md
As discussed in #75 , this PR changes the spec Python examples to use canonical initializers for the `*Spec` classes.
=> canonic initializers for Python examples

specification.md
This is meant to address #33, but goes a bit beyond that in that every class has a constructors section that either defines constructors or mentions why it doesn't.
=> Added constructors or notes that there are no declared constructors.

specification.md
Removed most references to V1 in the J/PSI jobspec.  While doing so, I noticed that we do have the `version` key in the YAML, which was undefined in the appendix.  I added a section for that.  While we might not have any current plans to add new versions of the J/PSI jobspec, it seems prudent to leave the key in case we find a need to in the future. 
Also added a sentence to each top-level key's section to describe how it connects to the `JobSpec`, `JobAttributes`, and `ResourceSpec` classes.
Closes #78
=> Clarify jobspec versioning and Flux vs J/PSI jobspec

specification.md
#48 originally stated:
> I am assuming that whoever added this intended to track some "too many jobs in the queue" error from the LRM and act according to that. If so, it would be difficult to do this because we do not define a clear mechanism that could allow a clear way for a user to distinguish such an error from other errors. To state that differently, it's not impossible, but it isn't specified. One would have to rely on how the implementation happens to report errors of such type.
We don't have an explicit error for "too many jobs in the queue", but we do have a `isTransient` method for the `SubmitException`.  So I tweaked the example a bit to be a submission loop that continually attempts re-submission during transient issues using an exponential backoff algorithm.
Closes #18 …
=> Add additional examples

specification.md
This fixes a number of issues:
- "JobExecutor" was misspelled in a number of places as "JobExector"
- some code issues
- use JobExecutor.get_instance instead of JobExecutorFactory.get_instance
- a bunch of Job.specification references which should be Job.spec
=> Fix examples

specification.md
Reverts ExaWorks/job-api-spec#122
See #122
=> Revert "expand on the `getContext()` description"

CONTRIBUTING.md, README.md, specification.md
@danlaney - Completed initial copyedits, please reassign for review as needed.
- Capitalized all bullets, included terminal punctuation where appropriate
- Completed minor grammatical/typographical fixes
- Removed colons in introductory headers
- Fixed a few links 
- Standardized spelling of key terminology
- Treated "metadata" as one word
- Removed hyphens from re-use and similar
=> Copyedits for grammar and standardization

specification.md
Since `Job.cancel()` requires the job to hold an executor instance,
this property is implied but not explicit. Since jobs are submitted
using `JobExecutor.submit()`, the job does not get to see an executor
instance unless the executor explicitly communicattes a reference to
itself as part of the `submit()` call. However, if the property is not
defined in the spec, an executor implementation cannot know what property
to set unless it looks at the specifics of the implementation of the `Job`
class. But that also prevents the executor implementation from being
portable to other implementations of the PSI/J core classes.
An alternative solution might be to submit an attach jobs using 
`Job.submit(JobExecutor ex)` and `Job.attach(JobExecutor ex)`, but seems a 
bit forced given that the …
=> Added a `Job.executor` property.

specification.md
It supersedes #44 and fixes #22.
=> Added some assumptions and goals.

specification.md
It now also returns when states that follow after the waited states are reached. This addresses issue #129.
=> Updated the `wait()` method.

CONTRIBUTING.md, README.md, specification.md
Changes are spread across multiple documents. Most are optional but tighten up the language a bit.
**CONTRIBUTING.md**
- Text edits to streamline copy.
**README.md**
- Text edits to make bullet copy more active, less repetitive.
**specification.md**
- Overall: Streamlined content.
- Lines 9-91: The only edit I made here is line 17/18 (making "about" lowercase). I did not (intend to?) update the table of content links.
- Lines 138-176: Used bolding more consistently and extended bolded text to make the section more skimmable.
- Lines 223-240: Edited the bullets to create a parallel structure.
- Lines 398-1884: Added a line between a method/exception "definition" and further discussion when the discussion extends for 4+ lines. (It breaks up the copy and highlights the most important info.) …
=> Llnl edits

specification.md
Reformat to fit (snuggly) in 80 columns.
Where appropriate, also split method/property descriptions into a simple leading sentence followed by a detailed explanation.
Some minor edits, such as a missing period here and there.
=> Reformat to 80 cols

specification.md
constructor of `JobSpec` and have `executable` and `arguments` first so that we can write things like `JobSpec('ls', ['-al'])`
=> Move the `name` keyword arg from the first position in the Python

specification.md
This adds a Python constructor for `JobAttributes`, in line with other classes, such as `JobSpec` and `ResourceSpecV1` (fixes #161).
It also fixes the type declarations for `JobSpec`.
=> Add and fix python constructors

specification.md
The throttling example could occasionally lead to re-submission of the same job (because the counter increment wasn't protected by a critical section). This fixes it (fixes #163).
It also replaces some instantiations of `ResourceSpec` (which is abstract and cannot be instantiated) to `ResourceSpecV1` (this fixes #165).
=> Example fixes

specification.md
=> Removed reference to native_id from `JobStatus.getMetadata`
